import React, { useState, useEffect } from 'react';
import { Navbar } from './components/Navbar';
import { Hero } from './components/Hero';
import { Row } from './components/Row';
import { Modal } from './components/Modal';
import { searchMovies, resolveMovieImages } from './services/geminiService';
import { Movie } from './types';
import { FALLBACK_MOVIES, GENRES } from './constants';
import { MovieCard } from './components/MovieCard';

// Add some Tailwind custom animation
const tailwindConfig = `
<style>
@keyframes fadeIn {
  from { opacity: 0; }
  to { opacity: 1; }
}
.animate-fade-in {
  animation: fadeIn 0.5s ease-out;
}
@keyframes fadeInUp {
    from { opacity: 0; transform: translateY(20px); }
    to { opacity: 1; transform: translateY(0); }
}
.animate-fade-in-up {
    animation: fadeInUp 0.4s ease-out;
}
</style>
`;

const App: React.FC = () => {
  const [selectedMovie, setSelectedMovie] = useState<Movie | null>(null);
  const [searchResults, setSearchResults] = useState<Movie[] | null>(null);
  const [isSearching, setIsSearching] = useState(false);
  const [heroMovie, setHeroMovie] = useState<Movie | null>(null);

  useEffect(() => {
    // Resolve images for fallback movies so they have valid URLs (picsum or TMDB if we hardcoded them)
    const resolvedFallback = FALLBACK_MOVIES.map(m => resolveMovieImages(m));
    
    // Pick a random hero movie
    const random = resolvedFallback[Math.floor(Math.random() * resolvedFallback.length)];
    setHeroMovie(random);
  }, []);

  const handleSearch = async (query: string) => {
    setIsSearching(true);
    setSearchResults(null);
    const results = await searchMovies(query);
    setSearchResults(results);
    setIsSearching(false);
  };

  const clearSearch = () => {
    setSearchResults(null);
  };

  return (
    <div className="bg-[#141414] min-h-screen text-white pb-10 overflow-x-hidden font-sans">
      <div dangerouslySetInnerHTML={{ __html: tailwindConfig }} />
      
      <Navbar onSearch={handleSearch} onHome={clearSearch} />

      {/* Detail Modal */}
      {selectedMovie && <Modal movie={selectedMovie} onClose={() => setSelectedMovie(null)} />}

      {/* Main Content Area */}
      {searchResults !== null ? (
        <div className="pt-28 px-4 md:px-16 min-h-screen animate-fade-in">
          <h2 className="text-2xl font-bold mb-6 text-[#e5e5e5]">Search Results</h2>
          {isSearching ? (
             <div className="flex justify-center items-center h-64">
                <div className="animate-spin rounded-full h-12 w-12 border-t-2 border-b-2 border-red-600"></div>
             </div>
          ) : searchResults.length > 0 ? (
             <div className="grid grid-cols-2 md:grid-cols-4 lg:grid-cols-6 gap-y-8 gap-x-4">
               {searchResults.map(movie => (
                 <MovieCard key={movie.id} movie={movie} onClick={setSelectedMovie} />
               ))}
             </div>
          ) : (
            <div className="text-center text-gray-500 mt-20">
                <p className="text-xl">No matches found.</p>
                <p className="text-sm">Try searching for a genre like "Cyberpunk" or "80s comedy"</p>
            </div>
          )}
        </div>
      ) : (
        <>
          <Hero movie={heroMovie} onMoreInfo={setSelectedMovie} />
          
          {/* Reduced negative margin to prevent overlap with Hero text */}
          <div className="-mt-20 md:-mt-40 relative z-20 pl-0">
            {/* First row is Trending (Preloaded) */}
            <Row 
                title="Trending Now" 
                staticMovies={FALLBACK_MOVIES.map(m => resolveMovieImages(m))} 
                onMovieClick={setSelectedMovie} 
            />
            
            {/* Dynamic Rows generated by Gemini */}
            {GENRES.slice(1).map((genre, index) => (
              <Row 
                key={genre} 
                title={genre} 
                isLarge={index === 0} // First genre row is large
                onMovieClick={setSelectedMovie} 
              />
            ))}
          </div>
        </>
      )}

      {/* Footer */}
      <footer className="mt-20 px-4 md:px-16 py-12 text-[#808080] text-[13px] leading-tight bg-[#141414]">
        <div className="max-w-[980px] mx-auto">
            <div className="grid grid-cols-2 md:grid-cols-4 gap-4">
                <div className="space-y-3">
                    <p className="hover:underline cursor-pointer">Audio Description</p>
                    <p className="hover:underline cursor-pointer">Investor Relations</p>
                    <p className="hover:underline cursor-pointer">Legal Notices</p>
                </div>
                <div className="space-y-3">
                    <p className="hover:underline cursor-pointer">Help Center</p>
                    <p className="hover:underline cursor-pointer">Jobs</p>
                    <p className="hover:underline cursor-pointer">Cookie Preferences</p>
                </div>
                <div className="space-y-3">
                    <p className="hover:underline cursor-pointer">Gift Cards</p>
                    <p className="hover:underline cursor-pointer">Terms of Use</p>
                    <p className="hover:underline cursor-pointer">Corporate Information</p>
                </div>
                 <div className="space-y-3">
                    <p className="hover:underline cursor-pointer">Media Center</p>
                    <p className="hover:underline cursor-pointer">Privacy</p>
                    <p className="hover:underline cursor-pointer">Contact Us</p>
                </div>
            </div>
            <div className="mt-8">
                 <button className="border border-[#808080] px-4 py-2 hover:text-white text-xs transition mb-4">Service Code</button>
                 <p className="text-[11px]">© 1997-2024 StreamGen, Inc.</p>
            </div>
        </div>
      </footer>
    </div>
  );
};

export default App;